language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dariothornhill
  password:
    secure: YdZ4QdKoa+zQhWCw5Qie8PqMiCyeZ1Kd9mGOdyuTjdJwBgKfoE83kXprdrS//NkWl+vdyB3VTcFejhj8G2i3GhMHYA0Cjd7MIGVydcHKNE6r7ryGLYUVPbfFOByq0MClw7ZdXCutKUyk3RidAgemipF5ASHa9ykxI6ROoGVX2U25IGIOBzpQ1+eXJS47pyNsgszJbq752Mu1n2YD5mBDKaUUgZj6T8q1QLsC9ty4ZuIHhsEr4nYcevC02PTPFrXLQPNUtQ7VU5yMJdmwXxxG3Ql1PiXQEUDCvmE+lfiLlwf1smgJa1TewdI6q+AuvoU8lrYh8w063+UjylMEkGh1JHAYbknM6qwVkGxuZKVxjxswFwUoepu+a0zkLoDcfVo0oJVmU/MrLjhxNOPnsA6L0rA7hUXXvQ7V5Elo1UpW+tRF+fAm9i57NPBBKH5iR3gJz3Wv7Dj/dEWSGA+RzRykgq7zfaEhAAI1tEoK+pvgT/vKj6cjJv+hpeTI1ypwRGY4VuR5fWLq4TYRgzBGiR+9JMjwJn6FZQh3s6jxjt8dC3tZBfJR1wtbKXfHuG4K7kePgmCKRu/7BGQvK2/Xsy3bT4hC1cBHuZsKl/7z2UEEdCqTzt/YyppQ7EbsDelfp6ffDHKcqCl13jEDsJaGLHd1BvBQo7QDYrnpQqi7njnv8is=
  on:
    tags: true
    repo: dariothornhill/okex_rest_api_client
    python: 3.6
